version: '3'

services:
  # mock nodes for "web" service
  web1: &web
    hostname: web1
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul3 -client 0.0.0.0"
    volumes:
      - ./consul.d:/consul/config
  web2:
    hostname: web2
    <<: *web

  web3:
    hostname: web3
    <<: *web

  # syncs N9K object-group `web_servers` with consul service `web`
  n9k_updater:
    build: n9k_updater
    hostname: n9k_updater
    command: "agent -data-dir /consul/data -retry-join consul3 -client 0.0.0.0 -config-file consul_config.json"
    networks:
      - consul-demo

  # syncs ACI external EPG based upon consul service `web`
  aci_updater:
    build: aci_updater
    hostname: aci_updater
    command: "agent -data-dir /consul/data -retry-join consul3 -client 0.0.0.0 -config-file consul_config.json"
    networks:
      - consul-demo

  # consul cluster
  consul1: &consul-server
    hostname: consul1
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -server -retry-join consul3 -client 0.0.0.0"

  consul2:
    hostname: consul2
    <<: *consul-server

  consul3:
    hostname: consul3
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul-demo:
