version: '3'

services:

  web1: &web
    hostname: web1
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul3 -client 0.0.0.0"
    volumes:
      - ./consul.d:/consul/config
  web2:
    hostname: web2
    <<: *web

  web3:
    hostname: web3
    <<: *web

  consul1: &consul-server
    hostname: consul1
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -server -retry-join consul3 -client 0.0.0.0"

  consul2:
    hostname: consul2
    <<: *consul-server

  consul3:
    hostname: consul3
    <<: *consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  updater:
    build: updater
    hostname: updater
    links:
      - consul1:consul1
networks:
  consul-demo:
